version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/development/Dockerfile
    image: fdsh_gateway_dev:0.2.0
    depends_on:
      - mongodb
      - rabbitmq
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/fdsh_gateway:cached
      - rails_cache:/fdsh_gateway/tmp/cache
      - bundle:/bundle
      - node_modules:/fdsh_gateway/node_modules
      - packs:/fdsh_gateway/public/packs
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST:-amqp://rabbitmq}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST:-event_source}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_URL_EVENT_SOURCE=${RABBITMQ_URL_EVENT_SOURCE:-amqp://guest:guest@rabbitmq:5672}
      - RABBITMQ_USERNAME=${AMQP_USERNAME:-guest}
      - RAILS_ENV=${RAILS_ENV:-development}
    tmpfs:
      - /tmp
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && yarn install --check-files && bundle install && bundle exec puma -C config/puma.rb"

  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
      - ./.docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./.docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  bundle:
  rails_cache:
  node_modules:
  packs:
  mongodb:
  mongodb_config:
  rabbitmq_etc:
  rabbitmq_data:
  rabbitmq_logs:
