# frozen_string_literal: true

require 'spec_helper'
require 'medicare_metadata_setup'

RSpec.describe Fdsh::Rrv::Medicare::RrvBatchRequestDirector do

  before :all do
    DatabaseCleaner.clean
  end

  after :each do
    # delete the most recent manifest (the one generated by this spec)
    manifest_from_spec = Dir[Rails.root.join("rrv_outbound_files/SBE00ME.DSH.RRVIN.D*.IN.zip")].max { |f1, f2| File.mtime(f1) <=> File.mtime(f2) }
    File.delete(manifest_from_spec)
  end

  let(:create_application_requests) do
    (1..17).each do |index|
      Fdsh::Rrv::Medicare::Request::StoreApplicationRrvRequest.new.call({application_hash: "TEST_APPLICATION_#{index}".constantize})
    end
  end

  before do 
    create_application_requests
  end

  let(:params) do
    {
      assistance_year: 2022,
      transactions_per_file: 10000,
      outbound_folder_name: 'rrv_outbound_files'
    }
  end

  subject do
    described_class.new.call(params)
  end

  it "success" do
    expect(Transaction.count).to eq 17
    expect(subject.success?).to be_truthy
    expect(subject.success).to eq "rrv_outbound_files"
    expect(Dir[Rails.root.join("rrv_outbound_files/SBE00ME.DSH.RRVIN.D*.IN.zip")]).to be_present
  end
end
